# OneMoment: serve app under /onemoment/public
Alias /onemoment/public /var/www/html/public

<Directory /var/www/html/public>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

SetEnvIf X-Forwarded-Proto "https" HTTPS=on